### ISSUE TITLE
Taxon forwards in tree_of_life calls

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/otcetera#102]
Taxon ids that have been forwarded (e.g. 4947456)
https://tree.opentreeoflife.org/taxonomy/browse?name=4947456
are bounced by tree_of_life calls as pruned taxa, e.g.
```
curl -X POST  -H "content-type":"application/json" -H "accept":"application/json" https://api.opentreeoflife.org/v3/tree_of_life/induced_subtree --data '{"label_format": "id", "ott_ids": [4947456, 7661950]}'
```

Would it be easy to follow the forwards on the otcetera side, or do we want to require users to check for forwards first?

**Comment by bredelings** [comment]
otcetera has access to the taxonomy, so its probably simplest to do it there.

I have implemented this in #103 .

It seems to be working on devapi:

``` sh
curl 'https://devapi.opentreeoflife.org/v3/tree_of_life/node_info' -H 'Content-Type: application/json'   -d '{"node_id":"ott4947456"}'
```

**Comment by snacktavish** [comment]
yes! fixed on dev.

```curl -X POST  -H "content-type":"application/json" -H "accept":"application/json" https://devapi.opentreeoflife.org/v3/tree_of_life/induced_subtree --data '{"label_format": "id", "ott_ids": [4947456, 3598340, 5857287, 5859859, 5857304, 5859866]}'
```
(and same call fails on api)
Nice work!

**Comment by bredelings** [comment]
Fixed on api.

**Comment by snacktavish** [comment]
Nice! I just tried it out and it works great.
