### ISSUE TITLE
otc-intersection-of-ids would be nice

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/otcetera#20]
A complementary method to the existing ```otc-union-of-ids```, useful for pruning trees.

**Comment by josephwb** [comment]
This is not urgent; I am getting the intersection thing done in python.

**Comment by mtholder** [comment]
added with https://github.com/OpenTreeOfLife/otcetera/commit/46e6ea3d9de23a47c62de4a6b514a6a296d914f8

See https://github.com/OpenTreeOfLife/otcetera#finding-the-union-or-intersection-of-the-ott-ids-in-a-set-of-trees

Note that `otc-union-of-ids` has  become `otc-set-of-ids`

**Comment by josephwb** [comment]
Sweet. I think that will be useful.
