### ISSUE TITLE
Report (un)contested taxa

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/otcetera#26]
From discussions with @mtholder it seems that, because of the pruning of the taxonomy tree during subproblem decomposition, not all uncontested taxa become subproblems. Specifically, when a larger clade (say, Order) is unsampled, only the highest  node becomes a subproblem (and not the families, genera, etc. within that order).

I understand why this is done, but it makes it a little tricky to determine which taxa are uncontested; that is, we cannot assume that the lack of a subproblem for taxon X means that X is contested.

Desired results: a list of the uncontested taxa; that way, the contested taxa are known by complement. However, as the list of contested taxa may be much shorter, it might make more sense to report the list of contested taxa, instead.

gratuitous emoji: :notebook:

**Comment by josephwb** [comment]
[Please forgive the long, rambling message; thinking things out as I go. Please let me know if I've made a logical error.]

Ok, it looks like I can use the pruned `taxonomy.tre` from `step_6` to get at this. This is what I glean so far:

1. Anything that is a subproblem is _uncontested_ (possibly with tree support).
2. Anything that is in the full taxonomy tree but not in the pruned taxonomy tree is _uncontested_ (and unsampled by trees). These cannot be subproblems because of the taxonomy pruning procedure.
3. (_Most_) things in the pruned taxonomy tree but are not subproblems are contested.

I say "most" above because I've been playing with (reasonable, I think) fabricated data sets.

Take a higher taxon (say, Order) with just 1 immediate taxonomic descendant (say, Family) with 1 Genus (let's call it "_X_") and a whack of terminal taxa. If the Family (or Order) is a sampled terminal in a (let's say the only) source tree, all of the taxonomic descendants (here, Order through Family through Genus through terminals) appear in the pruned tree, but none (except the Order) appear as subproblems, despite being uncontested. 

So, this obviously involves "knuckles". What otcetera seems to do is collapse knuckles to the highest taxon. In the example above, the terminals appear in the Order subproblem. I understand why this is: obviously we do not want knuckles to be subproblems.

What is tricky here is that it is not immediately obvious what the contested status of Genus _X_ is: it is in both the full and pruned taxonomy trees, but is not a subproblem, which suggests it is _contested_.

We can go further: include a source tree that exhaustively (or not) samples _X_ plus some outgroup(s) and supports the monophyly of _X_. Here, _X_ is still not a subproblem, the new source tree appears in the subproblems for the Order. Is _X_ uncontested? Does it have any support, for that matter? Only by knowledge that _X_ is connected to the Order by knuckles can we see that it is _uncontested_ (and actually supported). 

I guess when knuckles are involved, it is more intuitive to consider the lowest taxon (here, _X_), rather than the highest taxon (Order); the contested status of the Order isn't really interesting, as it involves no splitting that could be either supported or refuted.

Anyway: hence this feature request. It would be much simpler to just have a list of contested taxa instead of checking the subproblems themselves. :wind_chime:

**Comment by mtholder** [comment]
So when you run otc-uncontested-decompose in the normal mode of verbosity (ie without using the flag to make it quiet, you should see lots of logs statements in the decomposition step that look like this:

    2015-09-21 14:11:32,260 INFO  [default]  exportOrCollapse for ott413471 outdegree = 15 numLoopTrees = 3 numLoops = 6
    2015-09-21 14:11:32,260 INFO  [default]     Contested

for a contested taxon. And like this:

    2015-09-21 14:11:32,260 INFO  [default]  exportOrCollapse for ott481972 outdegree = 56 numLoopTrees = 4 numLoops = 110
    2015-09-21 14:11:32,260 INFO  [default]     Uncontested
    2015-09-21 14:11:32,260 INFO  [default]      exporting ott481972  treeIndex = 7 name = pg_2539_6294.tre
    2015-09-21 14:11:32,261 INFO  [default]      exporting ott481972  treeIndex = 41 name = pg_2085_4317.tre
    2015-09-21 14:11:32,261 INFO  [default]      exporting ott481972  treeIndex = 42 name = pg_180_794.tre
    2015-09-21 14:11:32,262 INFO  [default]      exporting ott481972  treeIndex = 180 name = pg_2820_6566.tre
    2015-09-21 14:11:32,262 INFO  [default]      exporting ott481972  treeIndex = 210 name = pg_225_5991.tre
    2015-09-21 14:11:32,263 INFO  [default]      exporting ott481972  treeIndex = 484 name = TAXONOMY


for an uncontested one.

Will that output not give you what you want?

**Comment by josephwb** [comment]
Ok, thanks; I will try that.

**Comment by josephwb** [comment]
That seemed to work. Thanks for pointing me there @mtholder.

**Comment by josephwb** [comment]
This still seems like a useful feature, doesn't it?

**Comment by mtholder** [comment]
https://github.com/OpenTreeOfLife/otcetera/blob/master/supertree/parse-out-for-contested-uncontested.py
