### ISSUE TITLE
When all children are suppressed, parent should be too

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/otcetera#37]
I would have reported this in mtholder/otcetera, but issue submission seems to be disabled there.

Currently, smasher annotates taxa with 'flags', and synthesis uses the flags to decide whether a taxon is to be suppressed.  With this architecture we have innumerable cases like this one:

https://github.com/OpenTreeOfLife/feedback/issues/279

(I could probably find 5 or 10 other similar reports.)  Smasher cannot be responsible for taking care of suppressing these parent taxa all whose children are suppressed, because it doesn't know which flags will trigger suppression in synthesis. Therefore, the inference has to be done by synthesis - assuming this kind of design.

A different way to do this would be for smasher to keep track of what flags trigger suppression for synthesis, and take care of suppressing parents in this situation.  If this seems the right way to go, then an issue should be filed with the reference-taxonomy repository.

**Comment by jar398** [comment]
Another instance: https://github.com/OpenTreeOfLife/feedback/issues/259

**Comment by mtholder** [comment]
Hmm. There are some taxa ( namely those at the species rank or below) that could be legitimate even if they are empty. 
I'd like to keep propinquity out of the taxonomy editing business as much as possible. But we can certainly do it, if the taxonomy flags don't work for pruning.

**Comment by jar398** [comment]
The cases I'm talking about are not those at the species rank or below.

The taxonomy flags are not adequate for pruning.​

Why not do this in smasher?

**Comment by jar398** [comment]
Another instance just came in: https://tree.opentreeoflife.org/taxonomy/browse?id=719023
(from https://github.com/OpenTreeOfLife/feedback/issues/281 )

**Comment by mtholder** [comment]
You articulated the reason not to do it in smasher in the first comment of this issue: the set of a flags are a runtime argument to the propinquity system.
We can certainly implement the "prune if empty" rule if we are confident that we always want to prune empty taxa. The script for this step is actually in peyotl. I'll make an issue there.

**Comment by jar398** [comment]
"The set of a flags are a runtime argument to the propinquity system"
simply expresses a design decision made a long time ago. It is not a
technical reason for continuing to do things that way.

**Comment by hyanwong** [comment]
Here's another too (all fossil children: https://tree.opentreeoflife.org/opentree/argus/ottol@3620484/Gobiatidae)

**Comment by hyanwong** [comment]
And a few more: https://github.com/OpenTreeOfLife/feedback/issues/283, https://github.com/OpenTreeOfLife/feedback/issues/282.

Not sure if I should be creating new github issues for all of these?

**Comment by jar398** [comment]
At this point, if they look like further instances of the same problem,
there is not much point in reporting them, since they will all be handled
in the same way, without individual attention.

**Comment by hyanwong** [comment]
Yep - presumed as much. Cheers.

**Comment by hyanwong** [comment]
By the way, these are all very easy to spot - they are all single-word terminal taxa, often high up in the taxonomic hierarchy (these frogs are mostly visible from the Anura node). It does make e.g. the amphibian tree look a bit odd. Similarly near the root of the vascular plant tree (although here the issue, although technically down to the same issue, is taxonomically slightly different, as e.g. Equisetopsida should contain living taxa, but has been misplaced)

**Comment by mtholder** [comment]
Thanks for the reports @hyanwong . It is very helpful to have the feedback.
I created an issue (https://github.com/OpenTreeOfLife/peyotl/issues/151) in the tool that prunes the taxonomy. So I'll close this issue. We can reopen it if the problems persist in the next version of the tree.
