### ISSUE TITLE
Pass in newick to conflict api?

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/otcetera#94]
@LunaSare and I have two use cases we are curious about how to approach:
1) Matching all the nodes in a tree in phylesystem to nodes in the synth tree. We have an example at https://github.com/OpenTreeOfLife/python-opentree/blob/get-tree/examples/conflict.py whch works nicely, but only maps the in group nodes.

2) A newick (or nexson any other tree format) not in phylesystem with all the tips mapped to OpenTree taxa.  

Any rec's on how to accomplish one or both of these? 
It seems like one option for both would be passing an appropriately labelled newick in to the conflict api.

**Comment by bredelings** [comment]
We do this already in ws_wrapper.

You can pass in a newick tree to the conflict analysis using the `tree1newick` key.
https://github.com/OpenTreeOfLife/ws_wrapper/blob/057125a1fa96d83cb2919653788e1df8d6a436b5/ws_wrapper/views.py#L334

To get a phylesystem tree encoded in the right way, see:
https://github.com/OpenTreeOfLife/ws_wrapper/blob/057125a1fa96d83cb2919653788e1df8d6a436b5/ws_wrapper/views.py#L50

The trick is how to encode the labels, which is described by the `_nodeid_ottid` key in the line above.  
This is implemented in the peyotl code in `peyotl/nexson_syntax/__init__.py` as follows:

```
def _nodeid_ottid_labeller(nodeid, node, otu):
    if otu is not None and '^ot:ottId' in otu.keys():
        ottid = otu['^ot:ottId']
        return "_{}_ott{}".format(nodeid,ottid)
    else:
        return nodeid
```

**Comment by mtholder** [comment]
See https://github.com/OpenTreeOfLife/ws_wrapper/blob/master/ws_wrapper/views.py#L321

**Comment by bredelings** [comment]
curl -X POST 'https://api.opentreeoflife.org/v3/conflict/conflict-status' -d '{"tree1":"pg_99@tree5885","tree2":"synth"}'

**Comment by snacktavish** [comment]
Ah cool. This is the current wrapper - https://github.com/OpenTreeOfLife/python-opentree/blob/get-tree/opentree/ot_ws_wrapper.py#L54
Looks like we could extend to use a tree1newick argument.

**Comment by snacktavish** [comment]
Ah nice. So it should work along the lines of 
curl -X POST https://api.opentreeoflife.org/v3/conflict/conflict-status -d '{"tree1newick":"((ott1), node1(ott2));","tree2":"synth"}'

If you could post a lil newick that works we can spec off of that!

**Comment by mtholder** [comment]
Try:

     curl -X POST 'https://api.opentreeoflife.org/v3/conflict/conflict-status' -d '{"tree1newick":"(('_nd1_ott770315','newick_nd2_ott417950')'_nd3_','_nd4_ott158484')'_nd5';","tree2":"synth"}'

**Comment by mtholder** [comment]
(though I didn't intend that newick_nd to be part of the label)

otcetera's node label parsing is odd, and we should probably think of an alternative way to do this for the API. 
but I think this works for now.
