### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/otcetera#95]
on

    curl -X POST 'https://api.opentreeoflife.org/v3/conflict/conflict-status' -d '{"tree1":"(('_nd1_ott770315','_nd2_ott417950')'_nd3_','_nd4_ott158484')'_nd5';","tree2":"synth"}'

**Comment by bredelings** [comment]
I will take a look.

**Comment by bredelings** [comment]
Seems fixed.  Now returns
```
{
    "message": "[/v3/conflict/conflict-status] Error: Expected study@tree or study#tree, but got '((_nd1_ott770315,_nd2_ott417950)_nd3_,_nd4_ott158484)_nd5;'"
}
```
