### ISSUE TITLE
TNRS note

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/otcetera#96]
based on https://ropensci.org/tutorials/rotl_tutorial/ section: Get tree for a particular taxonomic group

 it appears that a search for "monotremes" used to return only "Montrema", but now it returns only "Monotheles"

**Comment by bredelings** [comment]
I would not be surprised if there are a number of differences, mainly because I haven't had time to compare the differences between taxomachine and tnrs yet.

So, `monotremes` doesn't match any name or synonym exactly.

With fuzzy matching, I'm see a match to both "Monotrema" and "Monotheles", although the "Monotheles" match has a higher score.  Maybe the r function takes the highest-scoring match if there are multiple matches?

In both cases, I think the edit-distance is 2.  But Monotheles -> Monotremes with 2 "substitutions", whereas Monotrema -> Monotremes with 1 substitution and 1 insertion.

**Comment by bredelings** [comment]
I admit I am kind of interested in making a substitution matrix where substitutions between vowels have a low penalty, but vowels <-> constants have a higher penalty.  Along those likes "tr" -> "th" should maybe be penalized.  However, this is probably beyond the scope of the present work and all that.

**Comment by snacktavish** [comment]
Yeah, I'm not really sure what behavior I expect! I just thought I'd mention the change.

**Comment by snacktavish** [comment]
From @bomeara on gitter:
"It now appears that looking up ot:focalCladeOTTTaxonName is now case sensitive. This gives studies:
curl -X POST https://api.opentreeoflife.org/v3/studies/find_studies -H "content-type:application/json" -d '{"property":"ot:focalCladeOTTTaxonName","value":"Mammalia","verbose":true}'
but this does not:
curl -X POST https://api.opentreeoflife.org/v3/studies/find_studies -H "content-type:application/json" -d '{"property":"ot:focalCladeOTTTaxonName","value":"mammalia","verbose":true}'
It came up b/c the R rotl package documentation has lower case examples that used to work but don't any longer -- it's easy enough to fix this in the documentation, but I just wanted to make sure this is intended behavior"

I think this is not intended, right?

**Comment by bredelings** [comment]
My first reaction was that otcetera must be doing something wrong, but it seems like this would be an otindex thing.

**Comment by mtholder** [comment]
It does seem like the following work:

    curl -X POST https://api.opentreeoflife.org/v3/tnrs/match_names -H "content-type:application/json" -d '{"names":["mammalia"]}'
    curl -X POST https://api.opentreeoflife.org/v3/tnrs/match_names -H "content-type:application/json" -d '{"names":["Mammalia"]}'
   curl -X POST https://api.opentreeoflife.org/v3/studies/find_studies -H "content-type:application/json" -d '{"property":"ot:focalCladeOTTTaxonName","value":"Mammalia","verbose":true}'

but 

    curl -X POST https://api.opentreeoflife.org/v3/studies/find_studies -H "content-type:application/json" -d '{"property":"ot:focalCladeOTTTaxonName","value":"mammalia","verbose":true}'

doesn't. So either an otindex issue or otindex is calling some part of the taxonomy/tnrs API other than match_names

**Comment by kcranston** [comment]
I agree that this is an otindex issue. Closing this and opening a new issue there.
